force-app/main/default/objects/Account/fields/My_Description__c.field-meta.xml
<CustomField>
    <fullName>My_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>My Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Emp_1__c/Emp_1__c.object-meta.xml
<CustomObject>
    <label>Emp1</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Address#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emp1s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Emp_1__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Emp_1__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Emp1s</relationshipLabel>
    <relationshipName>Emp_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Emp_1__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Emp#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/My_Description__c.field-meta.xml
<CustomField>
    <fullName>My_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>My Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>CG</fullName>
            </value>
            <value>
                <fullName>DL</fullName>
            </value>
            <value>
                <fullName>KA</fullName>
            </value>
            <value>
                <fullName>TL</fullName>
            </value>
            <value>
                <fullName>TN</fullName>
            </value>
            <value>
                <fullName>WB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Descr.cls
public class Descr {
    public void cusDes(){
        system.debug('**********Entered Into Program*********');
        list<Employee__c> emps = [SELECT Name, Name__c, My_Description__c, (select Employee__c,City__c,State__c from Emp_Addresses__r) FROM Employee__c LIMIT 1000];
		for(Employee__c emp: emps)
      	{
            String str = emp.My_Description__c;
        	emp.My_Description__c=' ';
            //update emps;
    		List<Emp_1__c> empAddList = emp.Emp_Addresses__r;
          	for(Emp_1__c add: empAddList){
                str = emp.My_Description__c;
                String str1 = 'City  = ';
                String str2 = add.City__c;
                String str3 = add.State__c;
                str += '; '+str2+', '+str3+'; ';
                system.debug('***Address of emp: '+emp.Name__c+'\t' +' are '+add.City__c);
                /*emp.My_Description__c = str;
                update emps;*/
    			system.debug('Updated data'+emps);
            }
            emp.My_Description__c = str;
      	}
        update emps;
        system.debug('**********Leaving from Program*********');  
    }    

    public void stanDes(){
        system.debug('**********Entered Into Program*********');
        list<Account> accs = [SELECT Name, My_Description__c, (select FirstName,LastName from Contacts) FROM Account LIMIT 1000];
		for(Account acc: accs)
      	{
            String str;
        	List<Contact> accAddList = acc.Contacts;
          	for(Contact add: accAddList){
                str = acc.My_Description__c;
                String str1 = add.FirstName;
                String str2 = add.LastName;
                str = str+'FirstName = '+str1+';  '+' LastName = '+str2+'; ';
                system.debug('***Contacts of acc: '+acc.Name+'\t' +' are '+add.FirstName);
                acc.My_Description__c = str;
                update accs;
    			system.debug('Updated data'+accs);
            }
        }
        system.debug('**********Leaving from Program*********');  
    }    
}