force-app/main/default/objects/Bidder__c/Bidder__c.object-meta.xml
<CustomObject>
    <label>Bidder</label>
    <nameField>
        <displayFormat>Bid-{0000}</displayFormat>
        <label>Bidder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bidder__c/fields/Contractor_Account__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor_Account__r</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Contractor_Account__r)</relationshipLabel>
    <relationshipName>Bidders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder__c/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor_Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders</relationshipLabel>
    <relationshipName>Bidders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bidders</relationshipLabel>
    <relationshipName>Bidders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quote_Approved__c.field-meta.xml
<CustomField>
    <fullName>Quote_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/icUSSalesGeneratePDF_Email.cls
/**
 * Created by Anil Mannem on 03-Aug-2020
 */
public class icUSSalesGeneratePDF_Email {
    
    static icLogicBidder.IClass logicBidder = (icLogicBidder.IClass) icObjectFactory.GetSingletonInstance('icLogicBidder');
    //static icLogicAttachment.IClass logicAttachment = (icLogicAttachment.IClass) icObjectFactory.GetSingletonInstance('icLogicAttachment');
    //static icLogicEmail.IClass logicEmail = (icLogicEmail.IClass) icObjectFactory.GetSingletonInstance('icLogicEmail');

    @AuraEnabled
    public static String generatePDFandEmail(String recordId) {
        String errorMessage = '';
        List<Bidder__c> bidderList = logicBidder.getBidderDetailsforPDF(recordId);
        Bidder__c bidder;
        if(!bidderList.isEmpty()) {
            bidder = bidderList[0];
        }
        if (bidder.Opportunity__r.Quote_Approved__c) {
            PageReference p = Page.US_Sales_Quote_PDF;
            p.getParameters().put('bidderID', recordId);

            String fileTitle = bidder.Opportunity__r.Name+' - '+bidder.Distributor_Account__r.Name+' - '+bidder.Contractor_Account__r.Name+' - Quote.pdf';

       //     logicAttachment.createDocumentInObject(recordId, fileTitle, fileTitle, p.getContentAsPDF());
                    
            Messaging.EmailFileAttachment emailAttach = new Messaging.EmailFileAttachment();
            emailAttach.setContentType('application/pdf');
            emailAttach.setFileName(fileTitle);
            emailAttach.setInline(false);
            emailAttach.Body = p.getContentAsPDF();
            
            String subject = 'US Sales Quote of '+bidder.Opportunity__r.Name+' - '+bidder.Distributor_Account__r.Name+' - '+bidder.Contractor_Account__r.Name+' pair';
            String body = 'Hi '+ '<name>'+'\n'+
                        'Thank you for the opportunity to quote the '+' <project name> '+' project you’re working on. '+
                        'I have gotten the pricing quote over to '+'<supplier name>'+', so they should be getting the '+
                        'pricing to you shortly.  Hopefully all our benefits will greatly help you on this one to increase '+
                        'your profits and deliver a solid product.  Based on the <total square size> squares, looks like we '+
                        'will save you '+'<squares saved from below data> '+'squares on this project due to our full square '+
                        'coverage, and that will be labor saved as well.  Also with our bigger sized shingles, that will be '+
                        '<# of shingles> '+'fewer shingles installed - so quicker production speed should help get you on to '+
                        'the next job quicker.  <provide additional short comments here if desired>.  I’ve listed out the'+
                        ' estimated stats below as well.';

            List<String> recipients = new List<String>{bidder.Owner.Email}; //Email of Sales Rep who creates the bidder record.
            List<String> ccRecipients = new List<String>();
            List<String> bccRecipients = new List<String>();
            List<String> entities = new List<String>();
            List<Messaging.EmailFileAttachment> attachments = new List<Messaging.EmailFileAttachment>();
            attachments.add(emailAttach);

            // EmailTemplate template = logicEmail.getEmailTemplateByDevName('US_Sales_FollowUp_Quote');
            // logicEmail.sendTemplateEmail(template, bidder.Owner, bidder.Opportunity__c, entities, attachments);
            // logicEmail.sendTemplateEmail(template, '0053600000944h4AAA', bidder.Opportunity__c, entities, attachments);
      //      logicEmail.sendPlainTextEmail(subject, body, recipients, ccRecipients, bccRecipients, entities, attachments);
        } else {
            errorMessage = 'Opportunity has to be Approved to Generate PDF';
        }
        return errorMessage;
    }
}