force-app/main/default/objects/Bidder__c/Bidder__c.object-meta.xml
<CustomObject>
    <label>Bidder</label>
    <nameField>
        <displayFormat>Bid-{0000}</displayFormat>
        <label>Bidder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bidders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bidder__c/fields/Contractor_Account__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor_Account__r</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders (Contractor_Account__r)</relationshipLabel>
    <relationshipName>Bidders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder__c/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor_Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bidders</relationshipLabel>
    <relationshipName>Bidders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bidders</relationshipLabel>
    <relationshipName>Bidders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bidder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Open&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quote_Approved__c.field-meta.xml
<CustomField>
    <fullName>Quote_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/icRepoBidder.cls
/**
 * Created by Anil Mannem on 03-Aug-2020
 */
public class icRepoBidder implements icIClass {

    public Object GetInstance() {
        return new Impl();
    }

    public Interface IClass {
        List<Bidder__c> getBidderInfo();
        List<Bidder__c> getBidderDetailsforPDF(String recordId);
        void updateBidderStatus(List<Bidder__c> bidderList);
    }

    public class Impl implements IClass {
        public List<Bidder__c> getBidderInfo() {
            return [SELECT  Name,
                            Opportunity__c,
                            //Unique_ID__c,
                            Status__c
                    FROM Bidder__c];
        }

		public List<Bidder__c> getBidderDetailsforPDF(String recordId) {
			return [SELECT Id, 
                            Name,
                            Owner.Email,
                           // Distributor_Account__r.Name,
                           // Contractor_Account__r.Name,
                            Opportunity__r.Name,
                            Opportunity__c,
                           // Opportunity__r.Type_of_Project__c,
                           // Opportunity__r.Account.Name,
                            //Opportunity__r.Est_Project_Start_Date__c,
//                            Opportunity__r.Est_Project_Completion__c,
                            //Opportunity__r.Estimated_Project_Size__c,
                            //Opportunity__r.Account.BillingAddress,
                            //Opportunity__r.Account.BillingStreet,
                            //Opportunity__r.Account.BillingCity,
                            //Opportunity__r.Quote_Approved__c,
                            Opportunity__r.Amount
                        FROM Bidder__c
                        WHERE Id =: recordId];
		}
        
        public void updateBidderStatus(List<Bidder__c> bidderList) {
            update bidderList;
        }
    }
}