force-app/main/default/objects/Emp_1__c/Emp_1__c.object-meta.xml
<CustomObject>
    <label>Emp1</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Address#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emp1s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Emp_1__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Emp_1__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Emp1s</relationshipLabel>
    <relationshipName>Emp_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Emp_1__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
            <value>
                <fullName>TX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Emp#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>CG</fullName>
            </value>
            <value>
                <fullName>DL</fullName>
            </value>
            <value>
                <fullName>KA</fullName>
            </value>
            <value>
                <fullName>TL</fullName>
            </value>
            <value>
                <fullName>TN</fullName>
            </value>
            <value>
                <fullName>WB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SOQLRelEg.cls
public class SOQLRelEg {
    public void parent2Child(){
        system.debug('Entered Into Parent2Child()');
        //Standard Object
        List<Account> accList = [Select Name, Phone, (Select Name from Contacts) from Account];
        for(Account a: AccList){
            System.debug('Account Name :'+a.Name+'a.Phone :'+a.Phone);
            List<Contact> con = a.Contacts;
            for(Contact c: con){
                system.debug('FirstName '+c.FirstName+'\tLastName '+c.LastName);
            }
        }
        //Custom Object
        
        system.debug('Leaving from Parent2Child()');
    }
    public void Child2Parent(){
        //Standard Objects
        List<Contact> conList = [SELECT Name, Phone, Account.Name from Contact];
        for(Contact c: ConList){
            system.debug('Name'+c.Name+'\tAccount Name'+c.Account.name);
        }
        //Custom Objects
        List<Emp_1__c> emp1List =[Select city__c,State__c, Employee__r.Name from Emp_1__c];
        for(Emp_1__c e1: emp1List){
            system.debug('Name'+e1.city__c+'\tEmployee Name'+e1.Employee__r.Name);
        }
    }

}