force-app/main/default/objects/Emp_1__c/Emp_1__c.object-meta.xml
<CustomObject>
    <label>Emp1</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Address#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emp1s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Emp_1__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Emp_1__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Emp1s</relationshipLabel>
    <relationshipName>Emp_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>{00}</displayFormat>
        <label>Emp#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <label>Technology</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>DBMS</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CollEg.cls
public with sharing class CollEg {
	public void listEg(){
		system.debug('**********Entered Into Program*********');
        list<Employee__c> emps = [SELECT Name,Name__c, (select Employee__c,City__c from Emp_Addresses__r) FROM Employee__c LIMIT 1000];
		system.debug(emps);
        system.debug('Total no.of Records are: '+emps.size());
        list<Emp_1__c> adds =[select City__c,Employee__c from Emp_1__c];
      	for(Employee__c emp: emps)
      	{     
            Integer i=0;
            List<Emp_1__c> empAddList = emp.Emp_Addresses__r;
          	i=empAddList.size();
            system.debug('*** Record '+ emp.Name+'\t of '+emp.Name__c+'\t'+' has '+ i + '  addresses');
        	for(Emp_1__c add: empAddList){
                system.debug('***Address of emp: '+emp.Name__c+'\t' +' are '+add.City__c);
            }
			system.debug('\n');
        }
		system.debug('**********Leaving from Program*********');  
       
/*	    list<Employee__c> newEmp = new list<Employee__c>(10);
        String str ='aasdfghjkl1';
        string tech ='Java';
		newEmp[1].Name__c = str;
		newEmp[1].Technology__c = tech;
		insert newEmp[1];  
     
        list<Employee__c> newEmpList = new list<Employee__c>();
        system.debug('*****: ' + newEmpList);
        for(Integer i=0; i<3; i++){
            Employee__c emp = new Employee__c();
            system.debug('********* the emp: '+ emp);
            emp.Name__c = 'Anil-'+i;
            system.debug('********* the emp-2: '+ emp);
            //insert emp;
            newEmpList.add(emp);
            system.debug('********* the emp-3: '+ emp);
        }
        insert newEmpList;
        
        
        
      list<Employee__c> newEmpList = new list<Employee__c>();
        system.debug('*****: ' + newEmpList);
        for(Integer i=0; i<10; i++){
            Employee__c emp = new Employee__c();
            system.debug('********* the emp: '+ emp);
            emp.Name__c = 'Anil'; 
            insert emp;
        }
	*/
	}
}