force-app/main/default/objects/Text_Encrypted__c/Text_Encrypted__c.object-meta.xml
<CustomObject>
    <label>Text Encrypted</label>
    <nameField>
        <displayFormat>T-{00}</displayFormat>
        <label>#Text</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Text Enc</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Text_Encrypted__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FirstName</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestTri.cls
public class TestTri {
    public void ins(){
    	list<Text_Encrypted__c> texts = new List<Text_Encrypted__c>();
        for(Integer i=1;i<=1;i++){
	    	Text_Encrypted__c t = new Text_Encrypted__c(FirstName__c='C '+i);
	    	texts.add(t);
        }
        insert texts;
    }
    public void del(){
       List<Text_Encrypted__c> t = [select Id,Name from Text_Encrypted__c where FirstName__c Like 'C%' ];
       system.debug('Record was '+t);
       delete t;
    }    
    public void updateAcc(){	
    	Text_Encrypted__c textToUpdate =[select FirstName__c from Text_Encrypted__c where  FirstName__c='C 1'];
    	textToUpdate.FirstName__C= 'C_1';
    	update textToUpdate;
    	system.debug('Updated data');
    }
}